### ISSUE TITLE
Metadata writing into custom field

### ISSUE THREAD

**Issue by Patyaeke** [eric-at-zd/metadata-writer#1]
Dear Eric,

You may could help to me a little bit . Could you please give me a tip how should I edit your metadata writing app to write the metadata into a custom field instead of comment ?

Thank you in advance,
Patrik Kaldi

**Comment by eric-at-zd** [comment]
Hey Patrik,

I threw [a branch together ](https://github.com/eric-at-zd/metadata-writer/tree/custom-field-example) where you can see how to do this. 

Hope this helps,

Eric
